### PR TITLE
Bump packages. Bump react-native version. React-Navigation 2.0 support.

### PR DESCRIPTION
**Pull request by Amurmurmur**

### CODE REVIEW

**Comment by Amurmurmur** [comment]
@skellock Is anybody going to look into this PR ?

**Comment by skellock** [comment]
I’ll ask the team if anyone can test. I’m swamped and need help.

**Comment by jamonholmgren** [comment]
Hey @Amurmurmur , just letting you know I'm aware of this PR. We are having some internal discussions around how we will support Andross next week, so I'll get back with you afterward.

**Comment by Amurmurmur** [comment]
@jamonholmgren @skellock Guys, what was the biggest motivation to switch from Redux to Mobx ?

**Comment by jamonholmgren** [comment]
@Amurmurmur The primary motivation was to reduce the amount of boilerplate with our state management code. We also really liked the MobX (and mobx-state-tree/MST) approach.

However, with our next boilerplate, Cyberdemon, we will be revisiting state management again. Stay tuned....

**Comment by Ragzzy-R** [comment]
Hey Guys! is this getting merged? We are starting a new project in our team and are looking to proceed with React-navigation 2.0. Is there a way we can currently use 2.0 with Andross?

**Comment by mlaco** [comment]
Hey @Ragzzy-R thanks for your patience. I don't know Andross well enough to merge myself, but I will try to get others' attention this week sometime; it's on my calendar now.

**Comment by Ragzzy-R** [comment]
Hi. @mlaco recently I came across a doc from react navigation saying that storing navigation data inside redux is not recommended and future updates won't run tests against them. So I've been wondering do we really need the helper functions to do the navigation the redux way? We are storing navigation data on local state in our current project and it's working fine for now. (I'm pretty new to react native so I might be overlooking some scenario which needs redux in navigation).

**Comment by jamonholmgren** [comment]
I truly appreciate @Amurmurmur's help on this, but since it's quite old now I'm going to close it. If you want to re-open a fresh PR with the latest 0.57 please feel free!

**Pull request closed without merging**
